#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "clickhouse"
name = "ClickHouse"
description.en = "ClickHouse is the fastest and most resource efficient open-source database for real-time apps and analytics."
description.fr = "ClickHouse est la base de données open source la plus rapide et la plus économe en ressources pour les applications et les analyses en temps réel."

version = "23.8~ynh1"

maintainers = ["pbrisacier@mncc.fr"]

[upstream]
# NB: Only the "license" key is mandatory. Remove entries for which there's no relevant data
license = "Apache-2.0"
website = "https://clickhouse.com/"
admindoc = "https://clickhouse.com/docs/en/install"
userdoc = "https://clickhouse.com/docs/en/getting-started/quick-start#4-create-a-table"
code = "https://github.com/ClickHouse/ClickHouse"

cpe = "cpe:2.3:a:clickhouse:clickhouse"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false

# FIXME: replace with true, false, or "not_relevant".
# Not to confuse with the "sso" key: the "ldap" key corresponds to wether or not a user *can* login on the app using
# its YunoHost credentials.
ldap = "?"

# FIXME: replace with true, false, or "not_relevant".
# Not to confuse with the "ldap" key: the "sso" key corresponds to wether or not a user is *automatically logged-in*
# on the app when logged-in on the YunoHost portal.
sso = "?"

# FIXME: replace with an **estimate** minimum disk and RAM requirements. e.g. 20M, 400M, 1G...
disk = "50M"
ram.build = "50M"
ram.runtime = "1G"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "path"
    default = "/clickhouse"

    [install.init_main_permission]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    # This won't be saved as setting and will instead be used to initialize the SSOwat permission
    type = "group"
    default = "visitors"

    [install.admin]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "user"

    [install.password]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    # Note that user-provided passwords questions are not automatically saved as setting
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those

    [resources.sources]

    [resources.sources.common-static]
    amd64.url = "https://packages.clickhouse.com/tgz/lts/clickhouse-common-static-23.3.22.3-amd64.tgz"
    amd64.sha256 = "46a0c6a2842315b750cc3bd1f9eba6b59ab2758595f7e8452814940d3f832360"

    #[resources.sources.common-static-dbg]
    #amd64.url = "https://packages.clickhouse.com/tgz/lts/clickhouse-common-static-dbg-23.3.22.3-amd64.tgz"
    #amd64.sha256 = "4c7c0ea6252b95662aeb00c436c8eb33f04e7d9961d97291286a28ca6a314acb"

    [resources.sources.server]
    amd64.url = "https://packages.clickhouse.com/tgz/lts/clickhouse-server-23.3.22.3-amd64.tgz"
    amd64.sha256 = "fad0ef056785263d7c7cb63bf484fba46aebea3e7e30aff803d503070400ebe2"

    [resources.sources.client]
    amd64.url = "https://packages.clickhouse.com/tgz/lts/clickhouse-client-23.3.22.3-amd64.tgz"
    amd64.sha256 = "b5f52d12a322acfa13066801d195b5fc04e66df467befec908c1d486d8c7565e"


    [resources.system_user]
    # This will provision/deprovision a unix system user

    [resources.install_dir]
    # This will create/remove the install dir as /var/www/$app
    # and store the corresponding setting $install_dir

    [resources.data_dir]
    # This will create/remove the data dir as /home/yunohost.app/$app
    # and store the corresponding setting $data_dir
    #subdirs = ['data', 'tmp', 'user_files']

    [resources.permissions]
    # This will configure SSOwat permission for $domain/$path/
    # The initial allowed group of user is configured via the init_main_permission question (public=visitors, private=all_users)
    main.url = "/"

    [resources.ports]
    # This will pick a random port for reverse-proxying and store it as the $port setting
    clickhouse_secure.default = 9440
    clickhouse_secure.exposed = "TCP"

    #[resources.apt]
    # This will automatically install/uninstall the following apt packages
    # and implicitly define the $phpversion setting as 8.0 (if phpX.Y-foobar dependencies are listed)
    #packages = ["apt-transport-https", "ca-certificates", "curl", "gnupg"]
    #extras.clickhouse.repo = "deb https://packages.clickhouse.com/deb lts main"
    #extras.clickhouse.key = "https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key"
    #extras.clickhouse.packages = ["clickhouse-server", "clickhouse-client"]
