#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

### Settings are automatically loaded as bash variables
### in every app script context, therefore typically these will exist:
### - $domain
### - $path
### - $language
### - $install_dir
### - $port
### ...

### For remove operations :
### - the core will deprovision every resource defined in the manifest **after** this script is ran
### this includes removing the install directory, and data directory (if --purge was used)

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

### This should be a symetric version of what happens in the install script

ynh_systemd_action --service_name="clickhouse-server" --action="stop" --log_path="/var/log/clickhouse-server/clickhouse-server.log"

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status "$app" >/dev/null; then
    ynh_script_progression --message="Removing $app service integration..." --weight=1
    yunohost service remove "$app"
fi

ynh_remove_nginx_config

# See: https://github.com/ClickHouse/ClickHouse/issues/38877#issuecomment-1590562695
for file in /usr/bin/clickhouse*; do
    # Vérifier si le fichier existe
    if [ -e "$file" ]; then
        # Supprimer le fichier
        ynh_secure_remove --file="$file"
    fi
done
ynh_secure_remove --file="/etc/clickhouse-server"
ynh_secure_remove --file="/lib/systemd/system/clickhouse-server.service"
ynh_secure_remove --file="/var/log/clickhouse-server"
ynh_secure_remove --file="/var/run/clickhouse-server"
ynh_secure_remove --file="/etc/security/limits.d/clickhouse.conf"


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
