#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Restoring the app main directory..." --weight=1

ynh_restore_file --origin_path="$install_dir"

### $install_dir will automatically be initialized with some decent
### permissions by default ... however, you may need to recursively reapply
### ownership to all files such as after the ynh_setup_source step
chown -R "$app:www-data" "$install_dir"

# I reapply clickhouse install scripts
$install_dir/common-static/install/doinst.sh
$install_dir/server/install/doinst.sh
$install_dir/client/install/doinst.sh

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression --message="Restoring the data directory..." --weight=1

ynh_restore_file --origin_path="$data_dir" --not_mandatory

### (Same as for install dir)
chown -R "$app:$app" "$data_dir"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Restoring system configurations related to $app..." --weight=1

ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"

# ynh_restore_file --origin_path="/lib/systemd/system/clickhouse-server.service"
# systemctl enable --quiet "clickhouse-server.service"

ynh_restore_file --origin_path="/etc/systemd/system/clickhouse-restart.service"
ynh_restore_file --origin_path="/etc/systemd/system/clickhouse-certificates.timer"
systemctl enable --quiet "clickhouse-certificates.timer"

yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"
yunohost service add "clickhouse-restart" --description="Clickhouse restart service" \
    --test_status="systemctl show clickhouse-restart.service  -p ActiveState --value | grep -v failed"


#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore_file --origin_path="/etc/clickhouse-server/"

### For apps with huge logs, you might want to not backup logs every time:
### The mkdir call is just here in case the log directory was not backed up.
### mkdir -p "/var/log/$app"
### chown $app:www-data "/var/log/$app"
### ynh_restore_file --src_path="/var/log/$app/" --not_mandatory
###
### For other apps, the simple way is better:
ynh_restore_file --origin_path="/var/log/clickhouse-server/"

#=================================================
# RELOAD NGINX AND THE APP SERVICE
#=================================================
ynh_script_progression --message="Reloading NGINX web server and $app's service..." --weight=1

ynh_systemd_action --service_name="clickhouse-server" --action="start" --log_path="/var/log/clickhouse-server/clickhouse-server.log"
ynh_systemd_action --service_name="clickhouse-restart.service" --action="disable"
ynh_systemd_action --service_name="clickhouse-certificates.timer" --action="start"

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --last
