#!/bin/bash


#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

### Settings are automatically loaded as bash variables
### in every app script context, therefore typically these will exist:
### - $domain
### - $path
### - $language
### - $install_dir
### - $port
### ...

### In the context of upgrade,
### - resources are automatically provisioned / updated / deleted (depending on existing resources)
### - a safety backup is automatically created by the core and will be restored if the upgrade fails

### This variable describes which upgrade type is occurring, allowing the script to handle different modes:
### - UPGRADE_PACKAGE if only the YunoHost package has changed
### - UPGRADE_APP if the upstream app version has changed
### If your package needs to handle other things, like same-version upgrades or downgrades, please
### check out the $YNH_APP_UPGRADE_TYPE variable that can contain DOWNGRADE and UPGRADE_SAME too.
# upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping $app's systemd service..." --weight=1

ynh_systemd_action --service_name="$app" --action="stop" --log_path="/var/log/$app/$app.log"
ynh_systemd_action --service_name="clickhouse-certificates.timer" --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
#ynh_script_progression --message="Ensuring downward compatibility..." --weight=1

### N.B. : the following setting migration snippets are provided as *EXAMPLES*
### of what you may want to do in some cases (e.g. a setting was not defined on
### some legacy installs and you therefore want to initiaze stuff during upgrade)

# If db_name doesn't exist, create it
# if [ -z "$db_name" ]; then
#     db_name=$(ynh_sanitize_dbid --db_name=$app)
#     ynh_app_setting_set --app=$app --key=db_name --value=$db_name
# fi

# If install_dir doesn't exist, create it
# if [ -z "$install_dir" ]; then
#     install_dir=/var/www/$app
#     ynh_app_setting_set --app=$app --key=install_dir --value=$install_dir
# fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Upgrading source files..." --weight=1

# See: https://clickhouse.com/docs/en/install#from-tgz-archives
# NOTA: I do not install clickhouse-common-static-dbg that seams not mandatory
# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --source_id=common-static --dest_dir="$install_dir/common-static"
ynh_setup_source --source_id=server --dest_dir="$install_dir/server"
ynh_setup_source --source_id=client --dest_dir="$install_dir/client"

### $install_dir will automatically be initialized with some decent
### permission by default ... however, you may need to recursively reapply
### ownership to all files such as after the ynh_setup_source step
chown -R "$app:www-data" "$install_dir"

# Create a shared SFTP directory
mkdir -p /home/shared/clickhouse
# Create user directories and link them to data_dir
mkdir -p /home/shared/clickhouse/user_files
ln -s /home/shared/clickhouse/user_files $data_dir/user_files
chown "$app:$app" "/home/shared/clickhouse/user_files"
mkdir -p /home/shared/clickhouse/user_defined
ln -s /home/shared/clickhouse/user_defined $data_dir/user_defined
chown "$app:$app" "/home/shared/clickhouse/user_defined"
mkdir -p /home/shared/clickhouse/user_scripts
ln -s /home/shared/clickhouse/user_scripts $data_dir/user_scripts
chown "$app:$app" "/home/shared/clickhouse/user_scripts"

chmod -R 777 /home/shared/clickhouse

$install_dir/common-static/install/doinst.sh
$install_dir/server/install/doinst.sh
$install_dir/client/install/doinst.sh

# Needed to give read access to YunoHost SSL certificates for the domain
usermod -a -G ssl-cert $app

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression --message="Updating $app's configuration files..." --weight=1

### Same as during install
###
### The file will automatically be backed-up if it's found to be manually modified (because
### ynh_add_config keeps track of the file's checksum)

chown "$app:$app" "/etc/clickhouse-server/config.xml"
mkdir -p "/etc/clickhouse-server/config.d/"
chown "$app:$app" "/etc/clickhouse-server/config.d/"
ynh_add_config --template="config.d/00-remove-unused-parts.xml" --destination="/etc/clickhouse-server/config.d/00-remove-unused-parts.xml"
ynh_add_config --template="config.d/ldap.xml" --destination="/etc/clickhouse-server/config.d/ldap.xml"
ynh_add_config --template="config.d/listen.xml" --destination="/etc/clickhouse-server/config.d/listen.xml"
ynh_add_config --template="config.d/logger.xml" --destination="/etc/clickhouse-server/config.d/logger.xml"
ynh_add_config --template="config.d/openSSL.xml" --destination="/etc/clickhouse-server/config.d/openSSL.xml"
ynh_add_config --template="config.d/paths.xml" --destination="/etc/clickhouse-server/config.d/paths.xml"
ynh_add_config --template="config.d/remove-log-tables.xml" --destination="/etc/clickhouse-server/config.d/remove-log-tables.xml"
ynh_add_config --template="config.d/tcp_port_secure.xml" --destination="/etc/clickhouse-server/config.d/tcp_port_secure.xml"
ynh_add_config --template="config.d/user_directories.xml" --destination="/etc/clickhouse-server/config.d/user_directories.xml"

chown "$app:$app" "/etc/clickhouse-server/users.xml"
mkdir -p "/etc/clickhouse-server/users.d/"
chown "$app:$app" "/etc/clickhouse-server/users.d/"
ynh_add_config --template="users.d/00-remove-unused-parts.xml" --destination="/etc/clickhouse-server/users.d/00-remove-unused-parts.xml"
ynh_add_config --template="users.d/admin.xml" --destination="/etc/clickhouse-server/users.d/admin.xml"
ynh_add_config --template="users.d/profiles.xml" --destination="/etc/clickhouse-server/users.d/profiles.xml"
ynh_add_config --template="users.d/quotas.xml" --destination="/etc/clickhouse-server/users.d/quotas.xml"

### For more complex cases where you want to replace stuff using regexes,
### you shoud rely on ynh_replace_string (which is basically a wrapper for sed)
### When doing so, you also need to manually call ynh_store_file_checksum
###
### ynh_replace_string --match_string="match_string" --replace_string="replace_string" --target_file="$install_dir/some_config_file"
### ynh_store_file_checksum --file="$install_dir/some_config_file"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Upgrading system configurations related to $app..." --weight=1

### This should be a literal copypaste of what happened in the install's "System configuration" section

ynh_add_nginx_config

mkdir -p /var/log/clickhouse-server
chown "$app:$app" /var/log/clickhouse-server
#yunohost service add "clickhouse-server" --needs_exposed_ports "$port_clickhouse_secure" --description="ClickHouse Server" --log="/var/log/clickhouse-server/clickhouse-server.log"

# Configuration for systemd timer to restart Clickhouse server
# A restart is needed to load new LE certificates for secure port (9440)
ynh_add_systemd_config --service="clickhouse-restart" --template="systemd_clickhouse-restart.service"
_ynh_add_config_j2 --template="systemd_clickhouse-certificates.timer.j2" --destination="/etc/systemd/system/clickhouse-certificates.timer"

#yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting $app's systemd service..." --weight=1

# Start a systemd service
ynh_systemd_action --service_name="clickhouse-server" --action="start" --log_path="/var/log/clickhouse-server/clickhouse-server.log"

# Enable and start systemd service and timer to restart Clickhouse server
# A restart is needed to load new LE certificates for secure port (9440)
ynh_systemd_action --service_name="clickhouse-certificates.timer" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
